language: haskell
before_install:
  - sudo apt-get update -qq
  - git clone --quiet git://github.com/diagrams/monoid-extras.git diagrams/monoid-extras
  - git clone --quiet git://github.com/diagrams/dual-tree.git diagrams/dual-tree
  - git clone --quiet git://github.com/diagrams/diagrams-core.git diagrams/diagrams-core
  - git clone --quiet git://github.com/diagrams/diagrams-lib.git diagrams/diagrams-lib
  - cd diagrams
  - cabal install monoid-extras/ dual-tree/ diagrams-core/ diagrams-lib/
  - cd ..

notifications:
  irc:
    channels:
      - irc.freenode.org#diagrams
    skip_join: true
    template:
      - "\x0313diagrams-postscript\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
